### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by mhf-ir** [fabiospampinato/icon-font-buildr#7]
```
$ npm -v
6.13.4
$ nodejs -v
v12.14.1
$ uname -a
Linux usr1-laptop 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

```
  "devDependencies": {
    "icon-font-buildr": "^1"
   }
```
```
# npm install


> ttf2woff2@2.0.3 install /home/usr1/project/path/node_modules/ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

../csrc/addon.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE convert(Nan::NAN_METHOD_ARGS_TYPE)’:
../csrc/addon.cc:10:49: error: no matching function for call to ‘v8::Value::ToObject()’
   Local<Object> inputBuffer = info[0]->ToObject();
                                                 ^
In file included from /home/usr1/.cache/node-gyp/12.14.1/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../csrc/addon.cc:1:
/home/usr1/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/home/usr1/.cache/node-gyp/12.14.1/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/usr1/.cache/node-gyp/12.14.1/include/node/v8-internal.h:14:0,
                 from /home/usr1/.cache/node-gyp/12.14.1/include/node/v8.h:25,
                 from /home/usr1/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../csrc/addon.cc:1:
/home/usr1/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note: candidate: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/home/usr1/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/usr1/.cache/node-gyp/12.14.1/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/home/usr1/.cache/node-gyp/12.14.1/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
make: *** [Release/obj.target/addon/csrc/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-76-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/usr1/project/path/node_modules/ttf2woff2
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
```

**Comment by mhf-ir** [comment]
I think ttf2woff2 must be update.
Please bump version for this issue. Node.js 13 is already exist and 12 is latest lts version.
https://github.com/nfroidure/ttf2woff2/pull/51

**Comment by fabiospampinato** [comment]
Fixed, thanks 👍
